"""events org_timestamp index

Revision ID: f522d88d30c6
Revises: 98252dc932c9
Create Date: 2026-05-29 02:54:44.920035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f522d88d30c6'
down_revision: Union[str, None] = '98252dc932c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_events_org_timestamp', 'events', ['org_id', sa.text('timestamp DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_org_timestamp', table_name='events')
    # ### end Alembic commands ###
